version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  build_and_analyze:
    machine: true  # <-- Use machine executor for Docker login to work properly
    steps:
      - checkout

      - run:
          name: Docker Login
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin

      - run:
          name: Install .NET SDK
          command: |
            sudo apt-get update
            sudo apt-get install -y dotnet-sdk-7.0
            dotnet --version

      - run:
          name: Install unzip
          command: sudo apt-get install -y unzip

      - run:
          name: Restore Dependencies
          command: dotnet restore

      - run:
          name: Build
          command: dotnet build --no-restore --configuration Release

      - run:
          name: Run Tests
          command: |
            dotnet test --no-restore --no-build --verbosity normal \
              /p:CollectCoverage=true \
              /p:CoverletOutputFormat=opencover \
              /p:CoverletOutput=TestResults/coverage.xml

      - sonarcloud/scan

workflows:
  build:
    jobs:
      - build_and_analyze
