version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.1.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:9.0-preview  
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: dotnet restore
      - run:
          name: Build
          command: dotnet build --no-restore
      - run:
          name: Run Tests
          command: dotnet test --no-build
      - sonarcloud/scan

workflows:
  build_and_analyze:
    jobs:
      - build
