version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  build_and_analyze:
    machine: true  # Use machine executor for full Docker & .NET install flexibility
    steps:
      - checkout

      - run:
          name: Docker Login
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin

      - run:
          name: Install .NET 7 SDK
          command: |
            wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
            chmod +x dotnet-install.sh
            ./dotnet-install.sh --version 7.0.119
            echo 'export DOTNET_ROOT=$HOME/.dotnet' >> $BASH_ENV
            echo 'export PATH=$PATH:$HOME/.dotnet:$HOME/.dotnet/tools' >> $BASH_ENV

      - run:
          name: Install unzip
          command: sudo apt-get install -y unzip

      - run:
          name: Restore Dependencies
          command: |
            source $BASH_ENV
            dotnet restore

      - run:
          name: Build
          command: |
            source $BASH_ENV
            dotnet build --no-restore --configuration Release

      - run:
          name: Run Tests with Coverage
          command: |
            source $BASH_ENV
            dotnet test --no-restore --no-build --verbosity normal \
              /p:CollectCoverage=true \
              /p:CoverletOutputFormat=opencover \
              /p:CoverletOutput=TestResults/coverage.xml

      - sonarcloud/scan

workflows:
  build:
    jobs:
      - build_and_analyze
