version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  build_and_analyze:
    docker:
      - image: cimg/dotnet:7.0.10  # ✅ Working .NET image
    steps:
      - checkout

      - run:
          name: Install unzip
          command: |
            sudo apt-get update && sudo apt-get install -y unzip

      - run:
          name: Install Dependencies
          command: dotnet restore

      - run:
          name: Build
          command: dotnet build --no-restore --configuration Release

      - run:
          name: Run Tests
          command: dotnet test --no-restore --no-build --verbosity normal

      - sonarcloud/scan

workflows:
  build:
    jobs:
      - build_and_analyze
